name: qms_application
description: "QMS DEV"
publish_to: 'none'
version: 0.3.2+2

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  d_button: ^0.0.10
  d_info: ^0.2.0
  d_input: ^0.1.3
  d_method: ^0.2.6
  d_session: ^0.0.2
  extended_image: ^8.2.0
  flutter_bloc: ^8.1.3
  gap: ^3.0.1
  get: ^4.6.6
  google_fonts: ^6.1.0
  http: ^1.2.0
  http_parser: ^4.0.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  dropdown_search: ^5.0.6
  permission_handler: ^11.3.1
  geolocator: ^13.0.1
  camera: ^0.10.0+4
  geocoding: ^2.0.4
  device_info_plus: ^10.1.2
  path: ^1.9.0
  path_provider: ^2.1.4
  mailer: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
